Adding ip comparator - Fixes #19
mumuki/mumuki-text-runner pull request #20
Opened 2018-06-12 04:32 UTC by rodri042

Fixes #19

2018-06-12 14:56 UTC, flbulgarelli requested changes
Great! But please add the missing `valid_ip` in `checker.rb` so that the comparator is usable :wink:. 

Add an integration test to check that it is actually wired.

2018-06-12 14:57 UTC, flbulgarelli commented
@rodri042 looks good but please fix my comment

2018-06-15 05:55 UTC, rodri042 commented
> @rodri042 looks good but please fix my comment

@flbulgarelli Done!

2018-06-15 13:54 UTC, flbulgarelli approved these changes

2018-06-15 13:55 UTC, merged